version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
  flask_app:
    container_name: flask-app
    image: flask-app:latest
    build: .
    environment:
      YOU_NAME: Adam